{
	"filelist":
		[
			"angular-1.4.5/angular.min.js", 
			"angular-1.4.5/angular-route.min.js", 
			"angular-1.4.5/angular-cookies.min.js", 
			"js/jquery.min.js", 
			"cropit/jquery.cropit.js",
			"angular_mobile/js/mobile-angular-ui.min.js", 
			"angular_mobile/js/mobile-angular-ui.gestures.min.js", 
			"js/bootstrap.min.js",
			"animsition/js/animsition.min.js"
		]
}
